# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Deploy
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Depoy Bicep file'
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'AzureRmPipeline-conn'
        subscriptionId: 'c88267eb-7f60-4620-bdac-44c5da10f56e'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'DevtestRG01'
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: 'main.bicep'
        csmParametersFile: 'main.parameters.json'
        deploymentMode: 'Validation'